[package]
name = "doke-gdext"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # Compile to dynamic C library for the gdext

[dependencies]
doke = "0.3.0"
godot = "0.3.5"
markdown = "1.0.0"
thiserror = "2.0.16"
yaml-rust2 = "0.10.3"
